version: "2"
sql:
  - schema: "schema.sql"
    queries: "queries"
    engine: "postgresql"
    gen:
      go:
        package: "generated"
        out: "generated"
        sql_package: "github.com/jackc/pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: false
        emit_empty_slices: true
