-- ============================================================
-- schema_merged.sql — auto-generated by merge_migrations.sh
-- Generated at: 2026-03-01T13:48:10Z
-- Source: /Volumes/External/Code/paywall-iap/backend/migrations/*.up.sql (sorted)
-- ============================================================


-- ------------------------------------------------------------
-- Migration: 001_create_users.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: users
-- ============================================================
-- Platform identity: Apple originalTransactionId or Google
-- obfuscatedExternalAccountId. This is the canonical persistent
-- identity that survives reinstalls and device resets.
-- device_id is stored for analytics only and MUST NOT be used
-- as a foreign key.

CREATE TABLE users (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform_user_id    TEXT UNIQUE NOT NULL,
    device_id           TEXT,
    platform            TEXT NOT NULL CHECK (platform IN ('ios', 'android')),
    app_version         TEXT NOT NULL,
    email               TEXT UNIQUE,
    ltv                 NUMERIC(10,2) DEFAULT 0,
    ltv_updated_at      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);

COMMENT ON TABLE users IS 'User accounts with platform-based identity';
COMMENT ON COLUMN users.platform_user_id IS 'Canonical platform identity (Apple: originalTransactionId, Google: obfuscatedExternalAccountId)';
COMMENT ON COLUMN users.device_id IS 'Device identifier for analytics only - DO NOT use as foreign key';
COMMENT ON COLUMN users.ltv IS 'Lifetime value - updated by worker job';


-- ------------------------------------------------------------
-- Migration: 002_create_subscriptions.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: subscriptions
-- ============================================================

CREATE TABLE subscriptions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id),
    status          TEXT NOT NULL CHECK (status IN ('active', 'expired', 'cancelled', 'grace')),
    source          TEXT NOT NULL CHECK (source IN ('iap', 'stripe', 'paddle')),
    platform        TEXT NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
    product_id      TEXT NOT NULL,
    plan_type       TEXT NOT NULL CHECK (plan_type IN ('monthly', 'annual', 'lifetime')),
    expires_at      TIMESTAMPTZ NOT NULL,
    auto_renew      BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

COMMENT ON TABLE subscriptions IS 'User subscriptions';
COMMENT ON COLUMN subscriptions.source IS 'Purchase source: iap (Apple/Google), stripe, or paddle';

-- Enforce single active subscription per user
CREATE UNIQUE INDEX idx_subscriptions_one_active
    ON subscriptions(user_id)
    WHERE status = 'active' AND deleted_at IS NULL;

-- Hot path: access check (called on every content open)
CREATE INDEX idx_subscriptions_access
    ON subscriptions(user_id, status, expires_at)
    WHERE deleted_at IS NULL;


-- ------------------------------------------------------------
-- Migration: 003_create_transactions.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: transactions
-- ============================================================
-- receipt_data stores only a SHA-256 hash of the raw receipt
-- for deduplication; the full encrypted receipt is stored as
-- a webhook_event payload.

CREATE TABLE transactions (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES users(id),
    subscription_id     UUID NOT NULL REFERENCES subscriptions(id),
    amount              NUMERIC(10,2) NOT NULL,
    currency            CHAR(3) NOT NULL,
    status              TEXT NOT NULL CHECK (status IN ('success', 'failed', 'refunded')),
    receipt_hash        TEXT,
    provider_tx_id      TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE transactions IS 'Payment transactions';
COMMENT ON COLUMN transactions.receipt_hash IS 'SHA-256 hash of receipt for deduplication';

-- Transaction history
CREATE INDEX idx_transactions_user
    ON transactions(user_id, created_at DESC);


-- ------------------------------------------------------------
-- Migration: 004_create_webhook_events.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: webhook_events
-- ============================================================
-- Inbox pattern for idempotent webhook processing

CREATE TABLE webhook_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider        TEXT NOT NULL CHECK (provider IN ('stripe', 'apple', 'google', 'paddle')),
    event_type      TEXT NOT NULL,
    event_id        TEXT NOT NULL,
    payload         JSONB NOT NULL,
    processed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE webhook_events IS 'Webhook event inbox for idempotent processing';

-- Unique constraint on provider+event_id for idempotency
CREATE UNIQUE INDEX idx_webhook_events_unique
    ON webhook_events(provider, event_id);

-- Index for unprocessed events
CREATE INDEX idx_webhook_events_unprocessed
    ON webhook_events(processed_at)
    WHERE processed_at IS NULL;

-- ============================================================
-- Table: admin_settings
-- ============================================================

CREATE TABLE admin_settings (
    key         TEXT PRIMARY KEY,
    value       JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE admin_settings IS 'Persisted admin dashboard configuration and settings';


-- ------------------------------------------------------------
-- Migration: 005_create_pricing_tiers.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: pricing_tiers
-- ============================================================

CREATE TABLE pricing_tiers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL UNIQUE,
    description     TEXT,
    monthly_price   NUMERIC(10,2),
    annual_price    NUMERIC(10,2),
    currency        CHAR(3) NOT NULL DEFAULT 'USD',
    features        JSONB,
    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

COMMENT ON TABLE pricing_tiers IS 'Product pricing tiers';


-- ------------------------------------------------------------
-- Migration: 006_create_grace_periods.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: grace_periods
-- ============================================================

CREATE TABLE grace_periods (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id),
    subscription_id UUID NOT NULL REFERENCES subscriptions(id),
    status          TEXT NOT NULL CHECK (status IN ('active', 'resolved', 'expired')),
    expires_at      TIMESTAMPTZ NOT NULL,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE grace_periods IS 'Subscription grace periods for failed renewals';

CREATE INDEX idx_grace_periods_user
    ON grace_periods(user_id, status)
    WHERE status = 'active';


-- ------------------------------------------------------------
-- Migration: 007_create_winback_offers.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: winback_offers
-- ============================================================

CREATE TABLE winback_offers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id),
    campaign_id     TEXT NOT NULL,
    discount_type   TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value  NUMERIC(10,2) NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('offered', 'accepted', 'expired', 'declined')),
    offered_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    accepted_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE winback_offers IS 'Winback discount offers for churned users';

CREATE UNIQUE INDEX idx_winback_offers_user_campaign
    ON winback_offers(user_id, campaign_id)
    WHERE status IN ('offered', 'accepted');


-- ------------------------------------------------------------
-- Migration: 008_create_analytics_aggregates.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: analytics_aggregates
-- ============================================================

CREATE TABLE analytics_aggregates (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    metric_name     TEXT NOT NULL,
    metric_date     DATE NOT NULL,
    metric_value     NUMERIC(20,2) NOT NULL,
    dimensions      JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE analytics_aggregates IS 'Pre-computed analytics aggregates for reporting';

CREATE UNIQUE INDEX idx_analytics_aggregates_unique
    ON analytics_aggregates(metric_name, metric_date, dimensions);


-- ------------------------------------------------------------
-- Migration: 009_create_admin_audit_log.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: admin_audit_log
-- ============================================================

CREATE TABLE admin_audit_log (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_id        UUID NOT NULL,
    action          TEXT NOT NULL,
    target_user_id  UUID,
    target_type     TEXT NOT NULL,
    details         JSONB,
    ip_address      TEXT,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE admin_audit_log IS 'Audit log for admin actions';

CREATE INDEX idx_admin_audit_log_admin
    ON admin_audit_log(admin_id, created_at DESC);
CREATE INDEX idx_admin_audit_log_target_user
    ON admin_audit_log(target_user_id, created_at DESC);


-- ------------------------------------------------------------
-- Migration: 023_create_experiment_lifecycle_audit_log.up.sql
-- ------------------------------------------------------------
CREATE TABLE experiment_lifecycle_audit_log (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id   UUID NOT NULL REFERENCES ab_tests(id) ON DELETE CASCADE,
    actor_type      TEXT NOT NULL CHECK (actor_type IN ('admin', 'system')),
    actor_id        UUID,
    source          TEXT NOT NULL,
    action          TEXT NOT NULL CHECK (action IN ('status_transition')),
    from_status     TEXT NOT NULL,
    to_status       TEXT NOT NULL,
    idempotency_key TEXT,
    details         JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_experiment_lifecycle_audit_log_idempotency
    ON experiment_lifecycle_audit_log(idempotency_key);

CREATE INDEX idx_experiment_lifecycle_audit_log_experiment
    ON experiment_lifecycle_audit_log(experiment_id, created_at DESC);

COMMENT ON TABLE experiment_lifecycle_audit_log IS 'Lifecycle audit trail for experiment status transitions from admin and system automation paths';


-- ------------------------------------------------------------
-- Migration: 010_create_dunning.up.sql
-- ------------------------------------------------------------
-- ============================================================
-- Table: dunning
-- ============================================================

CREATE TABLE dunning (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subscription_id UUID NOT NULL REFERENCES subscriptions(id),
    user_id         UUID NOT NULL REFERENCES users(id),
    status          TEXT NOT NULL CHECK (status IN ('pending', 'in_progress', 'recovered', 'failed')),
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    max_attempts    INTEGER NOT NULL DEFAULT 5,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    last_attempt_at TIMESTAMPTZ,
    recovered_at    TIMESTAMPTZ,
    failed_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE dunning IS 'Subscription dunning process for failed renewals';

CREATE INDEX idx_dunning_subscription
    ON dunning(subscription_id)
    WHERE status IN ('pending', 'in_progress');

CREATE INDEX idx_dunning_pending
    ON dunning(next_attempt_at)
    WHERE status IN ('pending', 'in_progress');


-- ------------------------------------------------------------
-- Migration: 011_add_user_roles.up.sql
-- ------------------------------------------------------------
-- Add role column to users table
ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin', 'superadmin'));

-- Create an index to quickly find admins
CREATE INDEX idx_users_role ON users(role) WHERE role != 'user';


-- ------------------------------------------------------------
-- Migration: 012_create_ab_tests_with_bandit.up.sql
-- ------------------------------------------------------------
-- Create ab_tests table with bandit support
CREATE TABLE ab_tests (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                TEXT NOT NULL,
    description         TEXT,
    status              TEXT NOT NULL CHECK (status IN ('draft', 'running', 'paused', 'completed')) DEFAULT 'draft',
    start_at            TIMESTAMPTZ,
    end_at              TIMESTAMPTZ,

    -- Bandit-specific columns
    algorithm_type      TEXT CHECK (algorithm_type IN ('thompson_sampling', 'ucb', 'epsilon_greedy')),
    is_bandit           BOOLEAN NOT NULL DEFAULT false,
    min_sample_size     INT DEFAULT 100,
    confidence_threshold NUMERIC(3,2) DEFAULT 0.95,
    winner_confidence   NUMERIC(3,2),

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    automation_policy   JSONB NOT NULL DEFAULT '{"enabled": false, "auto_start": false, "auto_complete": false, "complete_on_end_time": true, "complete_on_sample_size": false, "complete_on_confidence": false, "manual_override": false}'::jsonb,
    CONSTRAINT ab_tests_automation_policy_is_object CHECK (jsonb_typeof(automation_policy) = 'object')
);

-- Index for active experiments
CREATE INDEX idx_ab_tests_active ON ab_tests(status) WHERE status = 'running';

-- Comment for documentation
COMMENT ON TABLE ab_tests IS 'A/B test experiments with multi-armed bandit support';
COMMENT ON COLUMN ab_tests.algorithm_type IS 'Bandit algorithm: thompson_sampling, ucb, or epsilon_greedy';
COMMENT ON COLUMN ab_tests.is_bandit IS 'True if this experiment uses bandit optimization (vs fixed allocation)';
COMMENT ON COLUMN ab_tests.min_sample_size IS 'Minimum samples before bandit can declare winner';
COMMENT ON COLUMN ab_tests.confidence_threshold IS 'Statistical confidence threshold (0.95 = 95%)';
COMMENT ON COLUMN ab_tests.winner_confidence IS 'Current confidence level of the winning arm';
COMMENT ON COLUMN ab_tests.automation_policy IS 'Persisted automation rules for scheduler-driven experiment lifecycle management';


-- ------------------------------------------------------------
-- Migration: 013_create_ab_test_arms.up.sql
-- ------------------------------------------------------------
-- Create ab_test_arms table for experiment variants
CREATE TABLE ab_test_arms (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id   UUID NOT NULL REFERENCES ab_tests(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    description     TEXT,
    is_control      BOOLEAN NOT NULL DEFAULT false,
    traffic_weight  NUMERIC(3,2) NOT NULL DEFAULT 1.0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for arm lookup by experiment
CREATE INDEX idx_ab_test_arms_experiment ON ab_test_arms(experiment_id);

-- Index for control arm lookup
CREATE INDEX idx_ab_test_arms_control ON ab_test_arms(experiment_id, is_control) WHERE is_control = true;

-- Ensure traffic_weight is non-negative
CHECK (traffic_weight >= 0)

-- Comment for documentation
COMMENT ON TABLE ab_test_arms IS 'Arms (variants) for A/B test experiments';
COMMENT ON COLUMN ab_test_arms.is_control IS 'True if this is the control/baseline variant';
COMMENT ON COLUMN ab_test_arms.traffic_weight IS 'Initial traffic weight for bandit algorithms';


-- ------------------------------------------------------------
-- Migration: 014_create_ab_test_arm_stats.up.sql
-- ------------------------------------------------------------
-- Create ab_test_arm_stats table for bandit statistics
CREATE TABLE ab_test_arm_stats (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    arm_id          UUID NOT NULL UNIQUE REFERENCES ab_test_arms(id) ON DELETE CASCADE,

    -- Thompson Sampling parameters (Beta distribution)
    alpha           NUMERIC(10,2) NOT NULL DEFAULT 1.0,
    beta            NUMERIC(10,2) NOT NULL DEFAULT 1.0,

    -- Sample counts
    samples         INT NOT NULL DEFAULT 0,
    conversions     INT NOT NULL DEFAULT 0,

    -- Revenue tracking
    revenue         NUMERIC(15,2) NOT NULL DEFAULT 0.0,

    -- Computed metrics
    avg_reward      NUMERIC(10,4),

    -- Timestamps
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Constraints
    CHECK (alpha > 0),
    CHECK (beta > 0),
    CHECK (samples >= 0),
    CHECK (conversions >= 0),
    CHECK (conversions <= samples)
);

-- Index for stats lookup by arm
CREATE INDEX idx_ab_test_arm_stats_arm ON ab_test_arm_stats(arm_id);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_ab_test_arm_stats_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ab_test_arm_stats_updated_at
    BEFORE UPDATE ON ab_test_arm_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_ab_test_arm_stats_updated_at();

-- Comment for documentation
COMMENT ON TABLE ab_test_arm_stats IS 'Bandit statistics for experiment arms (Thompson Sampling parameters)';
COMMENT ON COLUMN ab_test_arm_stats.alpha IS 'Beta distribution alpha parameter (successes + prior)';
COMMENT ON COLUMN ab_test_arm_stats.beta IS 'Beta distribution beta parameter (failures + prior)';
COMMENT ON COLUMN ab_test_arm_stats.avg_reward IS 'Average reward per sample (revenue / samples)';


-- ------------------------------------------------------------
-- Migration: 015_create_ab_test_assignments.up.sql
-- ------------------------------------------------------------
-- Create ab_test_assignments table for user assignment tracking
CREATE TABLE ab_test_assignments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id   UUID NOT NULL REFERENCES ab_tests(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    arm_id          UUID NOT NULL REFERENCES ab_test_arms(id) ON DELETE CASCADE,

    -- Assignment timestamps
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '24 hours'),

    -- Ensure one active assignment per user per experiment
    CONSTRAINT unique_active_assignment UNIQUE (experiment_id, user_id)
        WHERE expires_at > now()
);

-- Index for active assignment lookup
CREATE INDEX idx_ab_test_assignments_active ON ab_test_assignments(experiment_id, user_id, expires_at)
    WHERE expires_at > now();

-- Index for cleanup of expired assignments
CREATE INDEX idx_ab_test_assignments_expires ON ab_test_assignments(expires_at)
    WHERE expires_at <= now();

-- Index for user's assignment history
CREATE INDEX idx_ab_test_assignments_user_history ON ab_test_assignments(user_id, assigned_at DESC);

-- Function to check if assignment is still valid
CREATE OR REPLACE FUNCTION is_assignment_active(expires_at TIMESTAMPTZ) RETURNS BOOLEAN AS $$
BEGIN
    RETURN expires_at > now();
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Comment for documentation
COMMENT ON TABLE ab_test_assignments IS 'User assignments to experiment arms with sticky 24h TTL';
COMMENT ON COLUMN ab_test_assignments.expires_at IS 'Assignment expiration - after this, user can be reassigned';
COMMENT ON COLUMN ab_test_assignments.assigned_at IS 'When the user was first assigned to this arm';
COMMENT ON FUNCTION is_assignment_active IS 'Check if an assignment is still valid (not expired)';


-- ------------------------------------------------------------
-- Migration: 016_create_matomo_staged_events.up.sql
-- ------------------------------------------------------------
-- Create matomo_staged_events table for event queue
CREATE TABLE matomo_staged_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      TEXT NOT NULL CHECK (event_type IN ('event', 'ecommerce', 'custom')),
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
    payload         JSONB NOT NULL,

    -- Retry tracking
    retry_count     INT NOT NULL DEFAULT 0,
    max_retries     INT NOT NULL DEFAULT 3,
    next_retry_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Status tracking
    status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'failed', 'sent')),

    -- Timestamps
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at         TIMESTAMPTZ,
    failed_at       TIMESTAMPTZ,
    error_message   TEXT
);

-- Index for processing pending events
CREATE INDEX idx_matomo_staged_events_pending ON matomo_staged_events(status, next_retry_at)
    WHERE status = 'pending' AND next_retry_at <= now();

-- Index for user's events
CREATE INDEX idx_matomo_staged_events_user ON matomo_staged_events(user_id, created_at DESC);

-- Index for cleanup of old sent events
CREATE INDEX idx_matomo_staged_events_cleanup ON matomo_staged_events(status, sent_at)
    WHERE status = 'sent' AND sent_at < NOW() - INTERVAL '30 days';

-- Index for failed events (for fallback storage)
CREATE INDEX idx_matomo_staged_events_failed ON matomo_staged_events(status, failed_at)
    WHERE status = 'failed' AND retry_count >= max_retries;

-- Comment for documentation
COMMENT ON TABLE matomo_staged_events IS 'Staged Matomo events for async delivery with retry support';
COMMENT ON COLUMN matomo_staged_events.event_type IS 'Type of event: event (standard), ecommerce (purchase), or custom';
COMMENT ON COLUMN matomo_staged_events.payload IS 'Event data as JSONB - category, action, revenue, items, etc.';
COMMENT ON COLUMN matomo_staged_events.next_retry_at IS 'When the event should be retried (exponential backoff)';
COMMENT ON COLUMN matomo_staged_events.status IS 'pending, processing, failed, or sent';

-- Function to calculate next retry time with exponential backoff
CREATE OR REPLACE FUNCTION calculate_next_retry(retry_count INT, max_retries INT) RETURNS TIMESTAMPTZ AS $$
DECLARE
    base_interval INTERVAL := INTERVAL '1 minute';
    max_interval INTERVAL := INTERVAL '1 hour';
    backoff_multiplier INT := 2;
    calculated_interval INTERVAL;
BEGIN
    IF retry_count >= max_retries THEN
        RETURN NULL; -- No more retries
    END IF;

    -- Exponential backoff: 1min, 2min, 4min, 8min, ..., max 1 hour
    calculated_interval := LEAST(
        base_interval * (backoff_multiplier ^ retry_count),
        max_interval
    );

    RETURN now() + calculated_interval;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Trigger to auto-calculate next_retry_at on insert
CREATE OR REPLACE FUNCTION set_matomo_event_initial_retry()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.next_retry_at IS NULL OR NEW.next_retry_at = '1970-01-01 00:00:00+00'::timestamptz THEN
        NEW.next_retry_at = now(); -- Ready for immediate processing
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_matomo_staged_events_insert
    BEFORE INSERT ON matomo_staged_events
    FOR EACH ROW
    EXECUTE FUNCTION set_matomo_event_initial_retry();

-- Function to update event status after successful send
CREATE OR REPLACE FUNCTION mark_matomo_event_sent(event_id UUID) RETURNS VOID AS $$
BEGIN
    UPDATE matomo_staged_events
    SET status = 'sent',
        sent_at = now(),
        next_retry_at = NULL
    WHERE id = event_id;
END;
$$ LANGUAGE plpgsql;

-- Function to mark event as failed and increment retry count
CREATE OR REPLACE FUNCTION mark_matomo_event_failed(event_id UUID, error_msg TEXT) RETURNS VOID AS $$
DECLARE
    current_retry_count INT;
    current_max_retries INT;
BEGIN
    SELECT retry_count, max_retries INTO current_retry_count, current_max_retries
    FROM matomo_staged_events
    WHERE id = event_id;

    IF current_retry_count >= current_max_retries THEN
        -- Permanent failure
        UPDATE matomo_staged_events
        SET status = 'failed',
            failed_at = now(),
            error_message = error_msg
        WHERE id = event_id;
    ELSE
        -- Retry with exponential backoff
        UPDATE matomo_staged_events
        SET retry_count = retry_count + 1,
            status = 'pending',
            next_retry_at = calculate_next_retry(retry_count + 1, max_retries),
            error_message = error_msg
        WHERE id = event_id;
    END IF;
END;
$$ LANGUAGE plpgsql;


-- ------------------------------------------------------------
-- Migration: 017_create_bandit_advanced.up.sql
-- ------------------------------------------------------------
-- =====================================================
-- Advanced Thompson Sampling Extensions - Migration 017
-- =====================================================

-- =====================================================
-- Section 1: Currency Conversion
-- =====================================================

-- Currency rates table
CREATE TABLE currency_rates (
    id SERIAL PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    target_currency VARCHAR(3) NOT NULL,
    rate DECIMAL(18,6) NOT NULL,
    source VARCHAR(50),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(base_currency, target_currency)
);

-- Add currency tracking to arm stats
ALTER TABLE ab_test_arm_stats
ADD COLUMN revenue_usd DECIMAL(18,2) DEFAULT 0,
ADD COLUMN original_currency VARCHAR(3),
ADD COLUMN original_revenue DECIMAL(18,2);

-- Index for currency rate lookups
CREATE INDEX idx_currency_rates_target ON currency_rates(target_currency);
CREATE INDEX idx_currency_rates_updated ON currency_rates(updated_at);

-- =====================================================
-- Section 2: Add window configuration to ab_tests
-- =====================================================

ALTER TABLE ab_tests
ADD COLUMN window_type VARCHAR(10) CHECK (window_type IN ('events', 'time', 'none')),
ADD COLUMN window_size INT DEFAULT 1000,
ADD COLUMN window_min_samples INT DEFAULT 100,
ADD COLUMN objective_type VARCHAR(20) NOT NULL DEFAULT 'conversion' CHECK (objective_type IN ('conversion', 'ltv', 'revenue', 'hybrid')),
ADD COLUMN objective_weights JSONB,
ADD COLUMN price_normalization BOOLEAN DEFAULT FALSE,
ADD COLUMN enable_contextual BOOLEAN DEFAULT FALSE,
ADD COLUMN enable_delayed BOOLEAN DEFAULT FALSE,
ADD COLUMN enable_currency BOOLEAN DEFAULT FALSE,
ADD COLUMN exploration_alpha DECIMAL(4,2) DEFAULT 0.30;

-- =====================================================
-- Section 3: Contextual Bandit (LinUCB)
-- =====================================================

-- User context cache
CREATE TABLE bandit_user_context (
    user_id UUID PRIMARY KEY,
    country VARCHAR(3),
    device VARCHAR(20),
    app_version VARCHAR(20),
    days_since_install INT,
    total_spent DECIMAL(12,2),
    last_purchase_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- LinUCB model parameters
CREATE TABLE bandit_arm_context_model (
    arm_id UUID PRIMARY KEY REFERENCES ab_test_arms(id) ON DELETE CASCADE,
    dimension INT NOT NULL DEFAULT 20,
    matrix_a JSONB NOT NULL DEFAULT '[]',
    vector_b JSONB NOT NULL DEFAULT '[]',
    theta JSONB NOT NULL DEFAULT '[]',
    samples_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for context lookups
CREATE INDEX idx_bandit_user_context_updated ON bandit_user_context(updated_at);
CREATE INDEX idx_bandit_arm_context_model_updated ON bandit_arm_context_model(updated_at);

-- =====================================================
-- Section 4: Sliding Window
-- =====================================================

-- Event tracking for sliding window
CREATE TABLE bandit_window_events (
    id BIGSERIAL PRIMARY KEY,
    experiment_id UUID NOT NULL REFERENCES ab_tests(id) ON DELETE CASCADE,
    arm_id UUID NOT NULL REFERENCES ab_test_arms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('impression', 'conversion', 'no_conversion')),
    reward_value DECIMAL(12,2),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for window queries
CREATE INDEX idx_bandit_window_events_experiment_arm ON bandit_window_events(experiment_id, arm_id);
CREATE INDEX idx_bandit_window_events_timestamp ON bandit_window_events(timestamp DESC);

-- =====================================================
-- Section 5: Delayed Feedback
-- =====================================================

-- Pending reward tracking
CREATE TABLE bandit_pending_rewards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id UUID NOT NULL REFERENCES ab_tests(id) ON DELETE CASCADE,
    arm_id UUID NOT NULL REFERENCES ab_test_arms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    converted BOOLEAN DEFAULT FALSE,
    conversion_value DECIMAL(12,2),
    conversion_currency VARCHAR(3),
    converted_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ
);

-- Conversion links (pending reward -> transaction)
CREATE TABLE bandit_conversion_links (
    pending_id UUID NOT NULL REFERENCES bandit_pending_rewards(id) ON DELETE CASCADE,
    transaction_id UUID NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pending_id, transaction_id)
);

-- Indexes for pending reward processing
CREATE INDEX idx_bandit_pending_rewards_expires ON bandit_pending_rewards(expires_at) WHERE converted = FALSE;
CREATE INDEX idx_bandit_pending_rewards_user ON bandit_pending_rewards(user_id, experiment_id);
CREATE INDEX idx_bandit_conversion_links_transaction ON bandit_conversion_links(transaction_id);

-- =====================================================
-- Section 6: Multi-Objective Hybrid System
-- =====================================================

-- Per-objective statistics
CREATE TABLE bandit_arm_objective_stats (
    id BIGSERIAL PRIMARY KEY,
    arm_id UUID NOT NULL REFERENCES ab_test_arms(id) ON DELETE CASCADE,
    objective_type VARCHAR(20) NOT NULL CHECK (objective_type IN ('conversion', 'ltv', 'revenue')),
    alpha DECIMAL(10,2) DEFAULT 1.0,
    beta DECIMAL(10,2) DEFAULT 1.0,
    samples BIGINT DEFAULT 0,
    conversions BIGINT DEFAULT 0,
    total_revenue DECIMAL(18,2) DEFAULT 0,
    avg_ltv DECIMAL(12,2),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(arm_id, objective_type)
);

-- Index for objective stats lookups
CREATE INDEX idx_bandit_arm_objective_stats_arm ON bandit_arm_objective_stats(arm_id);
CREATE INDEX idx_bandit_arm_objective_stats_type ON bandit_arm_objective_stats(objective_type);

-- =====================================================
-- Section 7: Helper Functions
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_bandit_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply timestamp trigger to all relevant tables
CREATE TRIGGER trg_bandit_user_context_updated_at
    BEFORE UPDATE ON bandit_user_context
    FOR EACH ROW
    EXECUTE FUNCTION update_bandit_timestamps();

CREATE TRIGGER trg_bandit_arm_context_model_updated_at
    BEFORE UPDATE ON bandit_arm_context_model
    FOR EACH ROW
    EXECUTE FUNCTION update_bandit_timestamps();

CREATE TRIGGER trg_bandit_arm_objective_stats_updated_at
    BEFORE UPDATE ON bandit_arm_objective_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_bandit_timestamps();

-- =====================================================
-- Section 8: Comments for Documentation
-- =====================================================

COMMENT ON TABLE currency_rates IS 'Exchange rates for currency conversion (USD base)';
COMMENT ON TABLE bandit_user_context IS 'Cached user attributes for contextual bandit features';
COMMENT ON TABLE bandit_arm_context_model IS 'LinUCB model parameters per arm (A matrix, b vector, theta)';
COMMENT ON TABLE bandit_window_events IS 'Event log for sliding window calculations';
COMMENT ON TABLE bandit_pending_rewards IS 'Pending conversions for delayed feedback handling';
COMMENT ON TABLE bandit_conversion_links IS 'Links pending rewards to actual transactions';
COMMENT ON TABLE bandit_arm_objective_stats IS 'Per-objective statistics for multi-objective optimization';

COMMENT ON COLUMN ab_tests.window_type IS 'Type of windowing: events, time, or none';
COMMENT ON COLUMN ab_tests.objective_type IS 'Optimization objective: conversion, ltv, revenue, or hybrid';
COMMENT ON COLUMN ab_tests.objective_weights IS 'JSON weights for hybrid objectives';
COMMENT ON COLUMN ab_tests.enable_contextual IS 'Enable LinUCB contextual bandit';
COMMENT ON COLUMN ab_tests.enable_delayed IS 'Enable delayed feedback handling';
COMMENT ON COLUMN ab_tests.enable_currency IS 'Enable currency conversion to USD';
COMMENT ON COLUMN ab_tests.exploration_alpha IS 'Exploration parameter for LinUCB (default 0.3)';

