#!/usr/bin/env bash
# merge_migrations.sh
# Merges all *.up.sql migration files (in order) into a single SQL file.
# Usage: ./scripts/merge_migrations.sh [output_file]
#   output_file defaults to backend/migrations/schema_merged.sql

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MIGRATIONS_DIR="$REPO_ROOT/backend/migrations"
OUTPUT="${1:-$REPO_ROOT/backend/migrations/schema_merged.sql}"

echo "Merging migrations from: $MIGRATIONS_DIR"
echo "Output file: $OUTPUT"

# Start fresh
{
  echo "-- ============================================================"
  echo "-- schema_merged.sql — auto-generated by merge_migrations.sh"
  echo "-- Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "-- Source: $MIGRATIONS_DIR/*.up.sql (sorted)"
  echo "-- ============================================================"
  echo ""
} > "$OUTPUT"

# Find and sort all .up.sql files numerically by prefix
mapfile -t FILES < <(find "$MIGRATIONS_DIR" -maxdepth 1 -name "*.up.sql" | sort)

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "ERROR: No *.up.sql files found in $MIGRATIONS_DIR" >&2
  exit 1
fi

for FILE in "${FILES[@]}"; do
  BASENAME="$(basename "$FILE")"
  echo "  + $BASENAME"
  {
    echo ""
    echo "-- ------------------------------------------------------------"
    echo "-- Migration: $BASENAME"
    echo "-- ------------------------------------------------------------"
    cat "$FILE"
    echo ""
  } >> "$OUTPUT"
done

LINE_COUNT=$(wc -l < "$OUTPUT")
echo ""
echo "Done. Merged ${#FILES[@]} files → $OUTPUT ($LINE_COUNT lines)"
